"""PDF 첨부 — GitHub Release public asset → Notion file 속성.

Private GitHub repo의 PDF는 인증 없이 fetch 불가. 두 가지 방법:

Option A (자동) — GitHub Release public asset:
    1. PDF를 release asset으로 업로드 (GitHub API)
    2. release asset URL은 public (인증 없이 접근 가능)
    3. Notion에 외부 file URL로 첨부

Option B (수동) — repo를 public으로 변경:
    사용자가 GitHub Settings → Repository visibility → public 변경 후
    raw URL (https://raw.githubusercontent.com/...) 직접 사용

사용법:
    python3 attach_pdf.py --ticker LNG --pdf-path ... --method github_release
    python3 attach_pdf.py --ticker LNG --method raw_url
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR.parent.parent / "github-notion-sync" / "scripts"))

try:
    from github_client import (
        get_token as gh_token, get_owner, get_repo, _headers as gh_headers,
    )
except ImportError:
    print("[attach_pdf] github_client not available — install github-notion-sync first")
    sys.exit(1)


def get_or_create_release(owner: str, repo: str, tag: str = "v0.5.0") -> dict:
    """Get existing release by tag or create new one."""
    import requests
    # Check existing
    r = requests.get(
        f"https://api.github.com/repos/{owner}/{repo}/releases/tags/{tag}",
        headers=gh_headers(), timeout=15,
    )
    if r.status_code == 200:
        return r.json()
    # Create new
    body = {
        "tag_name": tag,
        "name": f"Stock Analysis {tag}",
        "body": "PDF reports for all analyses (auto-generated by github-notion-sync v0.1.0).",
        "draft": False,
        "prerelease": False,
    }
    r = requests.post(
        f"https://api.github.com/repos/{owner}/{repo}/releases",
        headers=gh_headers(), json=body, timeout=20,
    )
    r.raise_for_status()
    return r.json()


def upload_release_asset(release_id: int, owner: str, repo: str,
                          file_path: Path, asset_name: Optional[str] = None) -> dict:
    """Upload PDF as release asset. Returns public URL."""
    import requests
    if not file_path.exists():
        raise FileNotFoundError(str(file_path))
    if not asset_name:
        asset_name = file_path.name

    # Check if asset with same name exists — delete first (for re-upload)
    r = requests.get(
        f"https://api.github.com/repos/{owner}/{repo}/releases/{release_id}/assets",
        headers=gh_headers(), timeout=15,
    )
    if r.status_code == 200:
        for asset in r.json():
            if asset.get("name") == asset_name:
                requests.delete(
                    f"https://api.github.com/repos/{owner}/{repo}/releases/assets/{asset['id']}",
                    headers=gh_headers(), timeout=15,
                )
                print(f"[attach_pdf] deleted existing asset: {asset_name}")
                break

    # Upload new
    headers = dict(gh_headers())
    headers["Content-Type"] = "application/pdf"
    upload_url = f"https://uploads.github.com/repos/{owner}/{repo}/releases/{release_id}/assets"
    with file_path.open("rb") as f:
        r = requests.post(
            f"{upload_url}?name={asset_name}",
            headers=headers, data=f, timeout=120,
        )
    r.raise_for_status()
    return r.json()


def attach_pdf_via_release(ticker: str, pdf_path: Path,
                            release_tag: str = "v0.5.0") -> str:
    """Top-level: upload PDF to GitHub Release, return public download URL."""
    owner, repo = get_owner(), get_repo()
    if not owner or not repo:
        raise RuntimeError("GITHUB_OWNER and GITHUB_REPO required")

    print(f"[attach_pdf] ensuring release {release_tag}...")
    release = get_or_create_release(owner, repo, release_tag)
    print(f"[attach_pdf] release: {release.get('html_url')}")

    asset_name = f"{ticker}_{pdf_path.name}"
    print(f"[attach_pdf] uploading {pdf_path.name} as {asset_name}...")
    asset = upload_release_asset(release["id"], owner, repo, pdf_path, asset_name)
    public_url = asset.get("browser_download_url")
    print(f"[attach_pdf] public URL: {public_url}")
    return public_url


def main():
    p = argparse.ArgumentParser(description="PDF attachment via GitHub Release public asset")
    p.add_argument("--ticker", required=True)
    p.add_argument("--pdf-path", required=True, help="Local PDF path")
    p.add_argument("--method", default="github_release",
                   choices=["github_release", "raw_url"])
    p.add_argument("--tag", default="v0.5.0", help="Release tag")
    args = p.parse_args()

    if args.method == "github_release":
        url = attach_pdf_via_release(args.ticker, Path(args.pdf_path), args.tag)
        print(f"\n✓ PDF asset URL (public — usable in Notion):")
        print(url)
        print("\nTo add to Notion DB, update the row's 'PDF Report' property with this URL.")
    elif args.method == "raw_url":
        owner, repo = get_owner(), get_repo()
        rel_path = Path(args.pdf_path).resolve().as_posix().replace(str(Path.cwd().resolve()) + "/", "")
        url = f"https://raw.githubusercontent.com/{owner}/{repo}/main/{rel_path}"
        print(f"⚠️ This URL only works if the GitHub repo is PUBLIC.")
        print(f"Raw URL: {url}")


if __name__ == "__main__":
    main()
